name: 'Upload to S3'
description: 'Upload to S3'
inputs:
  source-filename:
    description: 'File to upload'
    required: true
    default: ''
  destination-filename:
    description: 'Target filename in s3'
    required: true
    default: ''
  host:
    description: 'Server endpoint'
    required: true
    default: 's3.bitfocus.io'
  bucket:
    description: 'Bucket to upload to'
    required: true
    default: ''
  access-key:
    description: 'Access Key'
    required: true
    default: ''
  secret-key:
    description: 'Secret Key'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    # Based on https://github.com/kneufeld/minio-put/blob/fe6c40f6fbade3e84926b8131b7eaf45966ff7e5/minio-put.sh
    - name: Upload file
      shell: bash
      run: |
        resource="/${{ inputs.bucket }}/${{ inputs.destination-filename }}"
        content_type="application/octet-stream"
        date=`date -R`
        _signature="PUT\n\n${content_type}\n${date}\n${resource}"
        signature=`echo -en ${_signature} | openssl sha1 -hmac ${{ inputs.secret-key }} -binary | base64`

        curl -v -X PUT -T "${{ inputs.source-filename }}" \
          --fail \
          -H "Host: ${{ inputs.host }}" \
          -H "Date: ${date}" \
          -H "Content-Type: ${content_type}" \
          -H "Authorization: AWS ${{ inputs.access-key }}:${signature}" \
          https://${{ inputs.host }}${resource}
