name: CompanionPi Build

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # publish-branch:
      #   type: choice
      #   description: Release branch (on the website)
      #   default: beta
      #   options:
      #     - stable
      #     - beta
      #   required: true
      companion-ref:
        type: string
        description: Companion tag to build as new stable
        default: beta
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build image

    steps:
      - name: Determine build details
        id: info
        shell: bash
        run: |
          DATE=$(date +"%m-%d-%y")

          echo ::set-output name=sourcename::"output-companionpi/image.gz"

          if [[ "${{ github.event_name }}" == "push" ]]
          then
            # Automatic beta build
            VERSION="0.0.0"
            echo ::set-output name=version::"${VERSION}+${{ github.run_number }}-${DATE}"
            echo ::set-output name=branch::"beta"
            echo ::set-output name=ref::"beta"
            echo ::set-output name=targetname::"companion-pi-beta-${{ github.run_number }}-${DATE}.img.gz"
          else
            # Manual stable build. We assume a semver tag was supplied
            echo ::set-output name=version::"${{ github.event.inputs.environment }}+${{ github.run_number }}-${DATE}"
            echo ::set-output name=branch::"stable"
            echo ::set-output name=ref::"${{ github.event.inputs.environment }}"
            echo ::set-output name=targetname::"companion-pi-stable-${{ github.event.inputs.environment }}-${DATE}.img.gz"
          fi
        
      - name: Do build
        uses: ./.github/actions/do-build
        with:
          companion-ref: ${{ steps.info.outputs.ref }}

      - name: Upload build
        uses: bitfocus/actions/upload-and-notify-for-branch@main
        with:
          source-filename: ${{ steps.info.outputs.sourcename }}
          destination-filename: ${{ steps.info.outputs.targetname }}
          s3-host: ${{ secrets.S3_HOST }}
          s3-bucket: ${{ secrets.S3_BUCKET }}/companion-pi
          s3-access-key: ${{ secrets.S3_KEY }}
          s3-secret-key: ${{ secrets.S3_SECRET }}

          api-version: ${{ steps.info.outputs.version }}
          api-branch: ${{ steps.info.outputs.branch }}
          api-product: companion-pi
          api-target: 'linux-img'
          api-secret: ${{ secrets.BITFOCUS_API_PROJECT_SECRET }}
