name: CompanionPi Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: build image
        run: |
          sudo packer init companionpi.pkr.hcl
          sudo packer build --var branch=master companionpi.pkr.hcl

      - name: compress image
        run: |
          cd output-companionpi
          gzip image

      - name: Determine files to upload
        if: github.ref == 'refs/heads/master' # always publish for just the master branch
        id: filenames
        shell: bash
        run: |
          DATE=$(date +"%m-%d-%y")

          echo ::set-output name=sourcename::"output-companionpi/image.gz"
          echo ::set-output name=targetname::"companionpi-${{ github.run_number }}-${DATE}.tar.gz"

      - name: Upload app
        if: ${{ steps.filenames.outputs.sourcename }}
        uses: ./.github/actions/s3-upload
        with:
          source-filename: ${{ steps.filenames.outputs.sourcename }}
          destination-filename: ${{ steps.filenames.outputs.targetname }}
          host: ${{ secrets.S3_HOST }}
          bucket: ${{ secrets.S3_BUCKET }}
          access-key: ${{ secrets.S3_KEY }}
          secret-key: ${{ secrets.S3_SECRET }}
